title: Malkion - Documentación
description: Documentación del módulo de recogida de datos en Odoo
baseurl: "/malkion"
url: "https://davidalbigarcia.github.io"
remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0
