title: Malkion - Documentación
description: Documentación del módulo de recogida de datos en Odoo
baseurl: "/datamalkion_mod1"
url: "https://DavidAlbiGarcia.github.io"
remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0
